#!/usr/bin/env bash
set -Eeuo pipefail

CONTAINER_NAME="${CONTAINER_NAME:-container-gitea}"
NETWORK_NAME="${NETWORK_NAME:-zap-vps-podman-network}"
IMAGE="${IMAGE:-docker.io/gitea/gitea:latest}"
PULL_POLICY="${PULL_POLICY:-missing}"
WEB_BIND="${WEB_BIND:-3000:3000}"
SSH_BIND="${SSH_BIND:-2222:22}"
HOST_DATA_DIR="${HOST_DATA_DIR:-$HOME/podman_data/gitea/data}"
TZ="${TZ:-Africa/Tunis}"
USER_UID="${USER_UID:-1000}"
USER_GID="${USER_GID:-1000}"
USERNS_MODE="${USERNS_MODE:-none}"
MEMORY_LIMIT="${MEMORY_LIMIT:-1g}"
CPU_SHARES="${CPU_SHARES:-1024}"
ENABLE_HARDENING="${ENABLE_HARDENING:-no}"
QUADLET_DIR="${QUADLET_DIR:-$HOME/.config/containers/systemd}"

log() {
  printf '[INFO] %s\n' "$*"
}

fail() {
  printf '[ERROR] %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing command: $1"
}

validate_pull_policy() {
  case "${PULL_POLICY,,}" in
    always|missing|newer|never)
      ;;
    *)
      fail "Invalid PULL_POLICY='$PULL_POLICY'. Allowed: always, missing, newer, never"
      ;;
  esac
}

ensure_image_prereq() {
  if [[ "${PULL_POLICY,,}" == "never" ]]; then
    if ! podman image exists "$IMAGE"; then
      fail "PULL_POLICY=never requires local image, but '$IMAGE' is not present."
    fi
    return
  fi

  if podman image exists "$IMAGE"; then
    return
  fi

  log "Image not found locally. Pulling once: $IMAGE"
  if podman pull "$IMAGE" >/dev/null; then
    return
  fi

  if [[ "$IMAGE" == docker.io/* ]]; then
    warn "Docker Hub unauthenticated pull rate limit likely hit."
    warn "Run: podman login docker.io"
    warn "Or override image registry, for example:"
    warn "  IMAGE=ghcr.io/go-gitea/gitea:latest bash container-gitea.sh"
  fi

  fail "Unable to pull image: $IMAGE"
}

service_name() {
  printf '%s.service' "$CONTAINER_NAME"
}

quadlet_file() {
  printf '%s/%s.container' "$QUADLET_DIR" "$CONTAINER_NAME"
}

is_unlimited() {
  case "${1,,}" in
    ""|none|off|no|unlimited|0)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

append_resource_limits() {
  local file="$1"

  if ! is_unlimited "$MEMORY_LIMIT"; then
    printf 'Memory=%s\n' "$MEMORY_LIMIT" >> "$file"
  fi

  if ! is_unlimited "$CPU_SHARES"; then
    printf 'PodmanArgs=--cpu-shares=%s\n' "$CPU_SHARES" >> "$file"
  fi
}

append_userns_mode() {
  local file="$1"

  if ! is_unlimited "$USERNS_MODE"; then
    printf 'UserNS=%s\n' "$USERNS_MODE" >> "$file"
  fi
}

ensure_network() {
  if ! podman network exists "$NETWORK_NAME"; then
    log "Creating network: $NETWORK_NAME"
    podman network create "$NETWORK_NAME" >/dev/null
  fi
}

prepare_storage() {
  install -d -m 755 "$HOST_DATA_DIR"
}

cleanup_legacy_deployments() {
  local legacy_service="container-${CONTAINER_NAME}.service"

  systemctl --user disable --now "$legacy_service" >/dev/null 2>&1 || true
  rm -f "$HOME/.config/systemd/user/$legacy_service"
  systemctl --user disable --now "$(service_name)" >/dev/null 2>&1 || true
  podman rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
}

write_quadlet_file() {
  local file
  file="$(quadlet_file)"

  mkdir -p "$QUADLET_DIR"

  cat > "$file" <<EOF
[Unit]
Description=Gitea container managed by Quadlet
After=network-online.target
Wants=network-online.target

[Container]
Image=${IMAGE}
ContainerName=${CONTAINER_NAME}
Pull=${PULL_POLICY}
Network=${NETWORK_NAME}
PublishPort=${WEB_BIND}
Environment=USER_UID=${USER_UID}
Environment=USER_GID=${USER_GID}
Environment=TZ=${TZ}
Volume=${HOST_DATA_DIR}:/data:Z
EOF

  if ! is_unlimited "$SSH_BIND"; then
    printf 'PublishPort=%s\n' "$SSH_BIND" >> "$file"
  fi

  append_resource_limits "$file"
  append_userns_mode "$file"

  if [[ "${ENABLE_HARDENING,,}" == "yes" ]]; then
    cat >> "$file" <<'EOF'
ReadOnly=true
Tmpfs=/tmp:rw,size=128m,nodev,nosuid
DropCapability=all
NoNewPrivileges=true
EOF
  fi

  cat >> "$file" <<'EOF'

[Service]
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

  log "Quadlet file written: $file"
}

reload_and_start_quadlet() {
  local svc
  svc="$(service_name)"

  systemctl --user daemon-reload

  if ! systemctl --user cat "$svc" >/dev/null 2>&1; then
    fail "Quadlet service was not generated by systemd. Check ${QUADLET_DIR}."
  fi

  systemctl --user start "$svc"

  if ! systemctl --user is-active --quiet "$svc"; then
    systemctl --user status "$svc" --no-pager || true
    journalctl --user -u "$svc" -n 80 --no-pager || true
    fail "Service did not stay active: $svc"
  fi

  if ! podman ps --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
    systemctl --user status "$svc" --no-pager || true
    journalctl --user -u "$svc" -n 80 --no-pager || true
    warn "If logs include 's6-svscan ... Permission denied', rerun with USERNS_MODE=none and ENABLE_HARDENING=no."
    fail "Container is not running: $CONTAINER_NAME"
  fi
}

print_summary() {
  printf '\nGitea is running.\n'
  printf 'Container: %s\n' "$CONTAINER_NAME"
  printf 'Image    : %s\n' "$IMAGE"
  printf 'Pull     : %s\n' "$PULL_POLICY"
  printf 'UserNS   : %s\n' "$USERNS_MODE"
  printf 'Network  : %s\n' "$NETWORK_NAME"
  printf '\nCommands:\n'
  printf '  systemctl --user status %s.service\n' "$CONTAINER_NAME"
  printf '  systemctl --user cat %s.service\n' "$CONTAINER_NAME"
  printf '  systemd-analyze --user --generators=true verify %s.service\n' "$CONTAINER_NAME"
  printf '  ls -l %s/%s.container\n' "$QUADLET_DIR" "$CONTAINER_NAME"
  printf '  journalctl --user -u %s.service -n 80 --no-pager\n' "$CONTAINER_NAME"
  printf '  podman logs -f %s\n' "$CONTAINER_NAME"

  printf '\nKeep mgrsys services running after logout:\n'
  printf '  sudo loginctl enable-linger mgrsys\n'
  printf '  loginctl show-user mgrsys -p Linger\n'
}

main() {
  require_command podman
  require_command systemctl
  validate_pull_policy

  ensure_network
  ensure_image_prereq
  prepare_storage
  cleanup_legacy_deployments
  write_quadlet_file
  reload_and_start_quadlet
  print_summary
}

main "$@"
