#!/usr/bin/env bash
set -Eeuo pipefail

CONTAINER_NAME="${CONTAINER_NAME:-container-cloudflare}"
SECRET_NAME="${SECRET_NAME:-cloudflare_tunnel_token}"
NETWORK_NAME="${NETWORK_NAME:-${SECRET_CLOUDFLARE:-zap-vps-podman-network}}"
IMAGE="${IMAGE:-docker.io/cloudflare/cloudflared:latest}"
METRICS_BIND="${METRICS_BIND:-0.0.0.0:2000}"
MEMORY_LIMIT="${MEMORY_LIMIT:-256m}"
CPU_SHARES="${CPU_SHARES:-512}"
QUADLET_DIR="${QUADLET_DIR:-$HOME/.config/containers/systemd}"

log() {
  printf '[INFO] %s\n' "$*"
}

fail() {
  printf '[ERROR] %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing command: $1"
}

service_name() {
  printf '%s.service' "${CONTAINER_NAME}"
}

quadlet_file() {
  printf '%s/%s.container' "${QUADLET_DIR}" "${CONTAINER_NAME}"
}

is_unlimited() {
  case "${1,,}" in
    ""|none|off|no|unlimited|0)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

append_resource_limits() {
  local file="$1"

  if ! is_unlimited "$MEMORY_LIMIT"; then
    printf 'Memory=%s\n' "$MEMORY_LIMIT" >> "$file"
  fi

  if ! is_unlimited "$CPU_SHARES"; then
    printf 'PodmanArgs=--cpu-shares=%s\n' "$CPU_SHARES" >> "$file"
  fi
}

ensure_secret() {
  if podman secret exists "$SECRET_NAME"; then
    log "Using existing secret: $SECRET_NAME"
    return
  fi

  printf 'Enter your Cloudflare tunnel token: '
  read -r -s tunnel_token
  printf '\n'

  [[ -n "$tunnel_token" ]] || fail "Token cannot be empty."
  printf '%s' "$tunnel_token" | podman secret create "$SECRET_NAME" - >/dev/null
  log "Secret created: $SECRET_NAME"
}

ensure_network() {
  if ! podman network exists "$NETWORK_NAME"; then
    log "Creating network: $NETWORK_NAME"
    podman network create "$NETWORK_NAME" >/dev/null
  fi
}

cleanup_legacy_deployments() {
  local legacy_service="container-${CONTAINER_NAME}.service"

  systemctl --user disable --now "$legacy_service" >/dev/null 2>&1 || true
  rm -f "$HOME/.config/systemd/user/$legacy_service"
  systemctl --user disable --now "$(service_name)" >/dev/null 2>&1 || true
  podman rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
  podman rm -f "containecloudflare" >/dev/null 2>&1 || true
}

write_quadlet_file() {
  local file
  file="$(quadlet_file)"

  mkdir -p "$QUADLET_DIR"

  cat > "$file" <<EOF
[Unit]
Description=Cloudflare tunnel container managed by Quadlet
After=network-online.target
Wants=network-online.target

[Container]
Image=${IMAGE}
ContainerName=${CONTAINER_NAME}
Pull=always
Network=${NETWORK_NAME}
ReadOnly=true
Tmpfs=/tmp:rw,size=32m,nodev,nosuid
DropCapability=all
NoNewPrivileges=true
Secret=${SECRET_NAME},type=env,target=TUNNEL_TOKEN
Exec=tunnel --no-autoupdate --metrics ${METRICS_BIND} run

EOF

  append_resource_limits "$file"

  cat >> "$file" <<'EOF'

[Service]
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

  log "Quadlet file written: $file"
}

reload_and_start_quadlet() {
  local svc
  svc="$(service_name)"

  systemctl --user daemon-reload

  if ! systemctl --user cat "$svc" >/dev/null 2>&1; then
    fail "Quadlet service was not generated by systemd. Check ${QUADLET_DIR}."
  fi

  # Generated Quadlet units cannot be enabled directly; start is the correct action.
  systemctl --user start "$svc"
}

print_summary() {
  printf '\nCloudflare tunnel is running.\n'
  printf 'Container: %s\n' "$CONTAINER_NAME"
  printf 'Secret   : %s\n' "$SECRET_NAME"
  printf 'Network  : %s\n' "$NETWORK_NAME"
  printf '\nCommands:\n'
  printf '  systemctl --user status %s.service\n' "$CONTAINER_NAME"
  printf '  systemctl --user cat %s.service\n' "$CONTAINER_NAME"
  printf '  podman logs -f %s\n' "$CONTAINER_NAME"
}

main() {
  require_command podman
  require_command systemctl

  ensure_secret
  ensure_network
  cleanup_legacy_deployments
  write_quadlet_file
  reload_and_start_quadlet
  print_summary
}

main "$@"
