#!/usr/bin/env bash
set -Eeuo pipefail

# Reusable rootless Podman template with native Quadlet output.
# Copy this script per app, or pass values as environment variables.

APP_NAME="${APP_NAME:-sample-app}"
IMAGE="${IMAGE:-docker.io/library/nginx:stable-alpine}"
NETWORK_NAME="${NETWORK_NAME:-zap-vps-podman-network}"
PUBLISH_PORT="${PUBLISH_PORT:-8080:80}"
HOST_DATA_DIR="${HOST_DATA_DIR:-$HOME/podman_data/${APP_NAME}/data}"
CONTAINER_DATA_DIR="${CONTAINER_DATA_DIR:-/var/lib/app}"
MEMORY_LIMIT="${MEMORY_LIMIT:-512m}"
CPU_SHARES="${CPU_SHARES:-${CPU_QUOTA:-1024}}"
ENABLE_HARDENING="${ENABLE_HARDENING:-yes}"
QUADLET_DIR="${QUADLET_DIR:-$HOME/.config/containers/systemd}"

log() {
  printf '[INFO] %s\n' "$*"
}

fail() {
  printf '[ERROR] %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing command: $1"
}

service_name() {
  printf '%s.service' "${APP_NAME}"
}

quadlet_file() {
  printf '%s/%s.container' "${QUADLET_DIR}" "${APP_NAME}"
}

is_unlimited() {
  case "${1,,}" in
    ""|none|off|no|unlimited|0)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

append_resource_limits() {
  local file="$1"

  if ! is_unlimited "${MEMORY_LIMIT}"; then
    printf 'Memory=%s\n' "${MEMORY_LIMIT}" >> "$file"
  fi

  if ! is_unlimited "${CPU_SHARES}"; then
    printf 'PodmanArgs=--cpu-shares=%s\n' "${CPU_SHARES}" >> "$file"
  fi
}

ensure_network() {
  if ! podman network exists "${NETWORK_NAME}"; then
    log "Creating network ${NETWORK_NAME}."
    podman network create "${NETWORK_NAME}" >/dev/null
  fi
}

prepare_storage() {
  install -d -m 755 "${HOST_DATA_DIR}"
}

cleanup_legacy_deployments() {
  local legacy_service="container-${APP_NAME}.service"

  systemctl --user disable --now "$legacy_service" >/dev/null 2>&1 || true
  rm -f "$HOME/.config/systemd/user/$legacy_service"
  systemctl --user disable --now "$(service_name)" >/dev/null 2>&1 || true
  podman rm -f "${APP_NAME}" >/dev/null 2>&1 || true
}

write_quadlet_file() {
  local file
  file="$(quadlet_file)"

  mkdir -p "${QUADLET_DIR}"

  cat > "$file" <<EOF
[Unit]
Description=${APP_NAME} container managed by Quadlet
After=network-online.target
Wants=network-online.target

[Container]
Image=${IMAGE}
ContainerName=${APP_NAME}
Network=${NETWORK_NAME}
PublishPort=${PUBLISH_PORT}
Volume=${HOST_DATA_DIR}:${CONTAINER_DATA_DIR}:Z
UserNS=keep-id
EOF

  append_resource_limits "$file"

  if [[ "${ENABLE_HARDENING}" == "yes" ]]; then
    cat >> "$file" <<'EOF'
ReadOnly=true
Tmpfs=/tmp:rw,size=64m,nodev,nosuid
DropCapability=all
NoNewPrivileges=true
EOF
  fi

  cat >> "$file" <<'EOF'

[Service]
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

  log "Quadlet file written: $file"
}

reload_and_start_quadlet() {
  local svc
  svc="$(service_name)"

  systemctl --user daemon-reload

  if ! systemctl --user cat "$svc" >/dev/null 2>&1; then
    fail "Quadlet service was not generated by systemd. Check ${QUADLET_DIR}."
  fi

  systemctl --user start "$svc"
}

print_hints() {
  cat <<'EOF'

Common issues and fixes:
1. SELinux denial on bind mounts:
   - Use :Z on mounts.
   - sudo restorecon -Rv "$HOME/podman_data"

2. UID/GID permission mismatch:
   - Keep --userns keep-id
   - podman unshare chown -R 1000:1000 "$HOME/podman_data/<app>"

3. User services stop after logout:
   - sudo loginctl enable-linger <user>

4. Rootless low-port binding (<1024):
   - sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80

5. Quadlet service inspection:
   - systemctl --user status <app>.service
   - systemctl --user cat <app>.service
EOF
}

main() {
  require_command podman
  require_command systemctl

  prepare_storage
  ensure_network
  cleanup_legacy_deployments
  write_quadlet_file
  reload_and_start_quadlet

  podman ps --filter "name=^${APP_NAME}$"
  print_hints
}

main "$@"
